name: flavor_redis_client
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.1+1
  
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.0.0+1
  flutter_localizations:
    sdk: flutter
  hive: ^2.0.6
  objectbox: 
  objectbox_flutter_libs: 
  flavor_auth:
    path: ../flavor/flavor_auth
  flavor_ui:
    path: ../flavor/flavor_ui
  flavor_http:
    path: ../flavor/flavor_http
  provider: ^6.0.2
  redis: ^2.2.0
  resp_client: ^1.2.0
  shared_preferences_windows: ^2.1.0
  web_socket_channel: ^2.1.0
  regex_router: ^2.0.0
  url_strategy: ^0.2.0

dev_dependencies:
  # build_runner:
  flutter_test:
    sdk: flutter
  # objectbox_generator: 

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
